--ASI SE CREA UNA TABLA "CREATE TABLE NOMBRE_TABLE("AQUI VAN LAS COLUMNAS");"
CREATE TABLE ASUNTO(
NUMERO_EXPEDIENTE NUMBER PRIMARY KEY,
CLIENTE_ID NUMBER,--CUANDO NO INDICAMOS LOS DECIMALES EN PARENTESIS ES UN ENTERO
FECHA_INICIO DATE,-- TIPO ESPECIAL DE LAS FECHAS
FECHA_ARCHIVO DATE,
COSTO NUMBER(7,3), --ASI ESPECIFICAMOS LOS NUMEROS ENTEROS ANTES DEL PUNTO
STATUS NVARCHAR2(15)
);

CREATE TABLE CLIENTE(
CLIENTE_ID NUMBER PRIMARY KEY,
INE NVARCHAR2(20),
NOMBRE NVARCHAR2(30),
DIRECCION NVARCHAR2(80),
FECHA_NAC DATE
);

CREATE TABLE PROCURADOR(
PROCURADOR_ID NUMBER PRIMARY KEY,
INE NVARCHAR2(20),
NOMBRE NVARCHAR2(50),
DIRECCION NVARCHAR2(100),
FECHA_NAC DATE
);

CREATE TABLE ASUNTO_PROC(
ASP NUMBER PRIMARY KEY,
ASUNTO_ID NUMBER,
PROCURADOR_ID NUMBER
);

--LLAVES FORANEAS 
--INDICAR LA TABLA QUE SE VA A ALTERAR, INDICAR QUE SE AGREGARA UNA CONSSTRAINT
ALTER TABLE ASUNTO ADD CONSTRAINT FK_ASUNTO_CLIENTE_ID
FOREIGN KEY(CLIENTE_ID)--INDICAR LA LLAVE FORANEA QUE SERVIRA DENTRO DE LA TABLA ASUNTO
REFERENCES CLIENTE(CLIENTE_ID);--INDICAR EL NOMBRE DE LA TABLE DE LA QUE PROVIENE ESA REFRENCIA

ALTER TABLE ASUNTO_PROC ADD CONSTRAINT FK_ASUNTO_PROC_ASUNTO_ID
FOREIGN KEY (ASUNTO_ID)
REFERENCES ASUNTO(NUMERO_EXPEDIENTE);

--hacemos constraint de procurador asunto_proc
ALTER TABLE ASUNTO_PROC ADD CONSTRAINT FK_ASUNTO_PROC_PROCURADOR_ID
FOREIGN KEY(PROCURADOR_ID)
REFERENCES PROCURADOR(PROCURADOR_ID);
--AQUI SELECCIONAMOS QUE DESEAMOS VER TODOS LOS REGISTROS DE LA TABLA CLIENTE
SELECT*FROM CLIENTE;

INSERT INTO CLIENTE 
--LOS IDS NO SE PUEDEN REPETIR UWU
VALUES(1,'12321312', 'PEDRO','CHOLULA',TO_DATE('01-12-1999','DD-MM-YYYY'));

INSERT INTO CLIENTE 
VALUES(2,'12321312', 'PEDRO','CHOLULA',TO_DATE('1999-12-01','YYYY-MM-DD'));













