CREATE TABLE TABLA(
ID_ZAPATO NUMBER PRIMARY KEY,
MARCA NVARCHAR2(30),
COLOR NVARCHAR2(10),
MODELO NVARCHAR2(20),
NUMERO_TALLA NUMBER
);

CREATE TABLE TABLA2(
TABLA1_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(30),
APELLIDOS NVARCHAR2(50),
FECHA_NAC DATE
);

CREATE TABLE TABLA3(
ID_PLAYERAS NUMBER PRIMARY KEY,
TALLAP NUMBER,
COLORP NVARCHAR2(10)
);

CREATE TABLE TABLA4(
ID_PANTALON NUMBER PRIMARY KEY,
MARCA_PAN NVARCHAR2(10),
TALLA_PAN NUMBER
);

CREATE TABLE TABLA5(
ID_SOMBREROS NUMBER PRIMARY KEY,
TALLA NUMBER

);

INSERT INTO TABLA3
VALUES(5,'2','BLANCO');

INSERT INTO TABLA4
VALUES(5,'DOCKERS','14');

INSERT INTO TABLA5
VALUES(5,30);

SELECT*FROM TABLA;

SELECT*FROM TABLA2;

SELECT*FROM TABLA3;

SELECT*FROM TABLA4;

SELECT*FROM TABLA5;
